/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela;

import LogicaBingo.Cartela;
import LogicaBingo.Jogador;
import javax.swing.JLabel;

/**
 *
 * @author Jonas
 */
public class PanelGUICartela extends javax.swing.JPanel {
    private Tela tela;
    private Cartela cartela;
    private Jogador jogador;
    
    private JLabel lbNumeros[][]= new JLabel[5][5];
    
    /**
     * Creates new form PanelGUICartela
     */
    public PanelGUICartela(Tela t, Cartela c, Jogador dono) {
        initComponents();
        tela=t;
        cartela=c;
        jogador=dono;
        
        //iniciando labels:
        for(int i=0; i<lbNumeros.length; i++){
            for(int j=0; j<lbNumeros[0].length; j++){
                lbNumeros[i][j]= new JLabel();
            }
        }
        
        setNumsInterface(c, dono);
        setLbId(c.getId());
        setLbJogador(dono.getNome());
    }
    
    public void setNumsInterface(Cartela cart, Jogador dono){
        int[][] cartela= cart.getCartela();
        String nome= dono.getNome();
        
        //labels com seus valores de acordo com a cartela
        for(int l=0; l<cartela.length; l++){
            for(int c=0; c<cartela[0].length; c++){
                String num;
                if(cartela[l][c]==0){
                    num= "--";
                }
                else if(cartela[l][c]<=9){
                    num= "0" + String.valueOf(cartela[l][c]);
                }
                else{
                    num= String.valueOf(cartela[l][c]);
                }
                
                lbNumeros[l][c].setText(num);
                
                //centralizando texto:
                lbNumeros[l][c].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                
                //adicionando borda
                lbNumeros[l][c].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
                
                //almentando tamanho da fonte
                lbNumeros[l][c].setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
                
                jpNumeros.add(lbNumeros[l][c]);
            }
        }
    }
    
    private void setLbId(int id){
        txtId.setText(("ID: " + String.valueOf(id)));
    }
    private void setLbJogador(String nome){
        txtNomeJogador.setText("Jogador: " + nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JLabel();
        txtNomeJogador = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jpNumeros = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARTELA");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        txtId.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        txtId.setText("ID: ");
        jPanel2.add(txtId);

        txtNomeJogador.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtNomeJogador.setText("Jogador: ");
        jPanel2.add(txtNomeJogador);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Trocar Cartela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jpNumeros.setBackground(java.awt.Color.gray);
        jpNumeros.setLayout(new java.awt.GridLayout(5, 5));
        add(jpNumeros, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cartela.gerarCartela();
        setNumsInterface(cartela, jogador);
        
        //lbNumeros[0][0].setText("kk");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpNumeros;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNomeJogador;
    // End of variables declaration//GEN-END:variables
}
