/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela;

import LogicaBingo.Jogador;

/**
 *
 * @author Jonas
 */
public class PanelInicial extends javax.swing.JPanel {
    
    private Tela tela;

    /**
     * Creates new form InicialPanel
     */
    public PanelInicial(Tela t, int qtNumCartela, int qtNumJogadores) {
        initComponents();
        tela=t;
        
        lbQtCartelas.setText(String.valueOf(qtNumCartela));
        lbQtJogadores.setText(String.valueOf(qtNumJogadores));
        
        //deixando o jdialog no centro:
        jdCompra.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCompra = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qtCartelasComprar = new javax.swing.JSpinner();
        btCancelar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btCompraCartela = new javax.swing.JButton();
        btSortear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbQtJogadores = new javax.swing.JLabel();
        lbQtCartelas = new javax.swing.JLabel();

        jdCompra.setMinimumSize(new java.awt.Dimension(200, 100));
        jdCompra.setModal(true);
        jdCompra.setSize(new java.awt.Dimension(300, 200));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel3.setText("nome (opicional):");
        jPanel1.add(jLabel3);
        jPanel1.add(jtNome);

        jLabel4.setText("Quantidade de Cartelas");
        jPanel1.add(jLabel4);

        qtCartelasComprar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(qtCartelasComprar);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar);

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btConfirmar);

        jdCompra.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);

        btCompraCartela.setBackground(new java.awt.Color(255, 255, 51));
        btCompraCartela.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btCompraCartela.setText("Adicionar Novo Jogador");
        btCompraCartela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraCartelaActionPerformed(evt);
            }
        });

        btSortear.setBackground(new java.awt.Color(0, 204, 0));
        btSortear.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btSortear.setText("Iniciar Sorteio");
        btSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade de Jogadores: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade de Cartelas:");

        lbQtJogadores.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbQtJogadores.setText("0");

        lbQtCartelas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbQtCartelas.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSortear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCompraCartela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbQtCartelas, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(lbQtJogadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQtJogadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQtCartelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCompraCartela, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btCompraCartelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraCartelaActionPerformed
        // TODO add your handling code here:
        //tela.irCompraCartela();
        
        jdCompra.setVisible(true);
    }//GEN-LAST:event_btCompraCartelaActionPerformed

    private void btSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortearActionPerformed
        // TODO add your handling code here:
        tela.irSorteio();
    }//GEN-LAST:event_btSortearActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        qtCartelasComprar.setValue(1);
        jtNome.setText("");
        //tela.fecharJdCompra();
        jdCompra.setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
        int qtCartelas= (int)(qtCartelasComprar.getValue());
        String nome = jtNome.getText()==null? "" : jtNome.getText();
        qtCartelasComprar.setValue(1);
        jtNome.setText("");

        //criando jogador
        Jogador jogador= new Jogador(nome, qtCartelas, tela.getBingo());

        //tela.fecharJdCompra();
        jdCompra.setVisible(false);

        tela.irDetalheCompra(jogador);
    }//GEN-LAST:event_btConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCompraCartela;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btSortear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog jdCompra;
    private javax.swing.JTextField jtNome;
    private javax.swing.JLabel lbQtCartelas;
    private javax.swing.JLabel lbQtJogadores;
    private javax.swing.JSpinner qtCartelasComprar;
    // End of variables declaration//GEN-END:variables
}
