/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela;

import LogicaBingo.Cartela;
import LogicaBingo.Jogador;
import baixarhtml.FileUploader;
import baixarhtml.GeradorDeQr;
import cartelahtml.ManipularCart;
import java.awt.GridLayout;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Jonas
 */
public class PanelDetalheCompra extends javax.swing.JPanel {
    
    private Tela tela;
    private JButton btCartelas[];
    
    private Jogador jogador;

    /**
     * Creates new form PanelDetalheCompra
     */
    public PanelDetalheCompra(Tela t, Jogador jogador) {
        initComponents();
        this.jogador= jogador;
        tela= t;
        
        int qtCartelas= jogador.getQtCartelas();
        
        
        //mudando o panel dos dados para gridLayout com a quantidade de linhas de acordo com a quantidade de cartelas + a linha dos botoes de como salvar cartela e duas colunas 
        panelDados.setLayout(new GridLayout(qtCartelas, 2, 0, 8));
        
        //um botao para cada cartela:
        btCartelas= new JButton[qtCartelas];
        
        for(int i=0; i<qtCartelas; i++){
            String cartelaNum= "Cartela " + String.valueOf(i+1);
            
            JLabel jlb= new JLabel(cartelaNum);
            btCartelas[i]= new JButton("Visualizar cartela");
            
            jlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            
            btCartelas[i].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    
                    Cartela cartelaExibir;
                    
                    //verificando qual botao foi apertado e mostrando a cartela de acordo 
                    for(int i=0; i<btCartelas.length; i++){
                        if(evt.getSource() == btCartelas[i]){
                            cartelaExibir= jogador.getCartelas().get(i);
                            //System.out.println("i");
                            tela.irCartela(cartelaExibir, jogador);
                            break;
                        }
                    }
                    
                }
            });
            
            panelDados.add(jlb);
            panelDados.add(btCartelas[i]);
        }
        
        //adicionando os botoes de como salvar cartela
//        JButton btImprimir= new JButton("Imprimir Cartelas");
//        JButton btVisualizarNoCll= new JButton("Marcar Pelo Celular");
//        
//        btVisualizarNoCll.addActionListener(new java.awt.event.ActionListener() {
//                public void actionPerformed(java.awt.event.ActionEvent evt) {
//                    
//                    try {
//                        ManipularCart mc= new ManipularCart();
//                        mc.addCartelas(jogador);
//                        
//                        GeradorDeQr gerarQr= new GeradorDeQr(FileUploader.getLinkDownload());
//                        
//                        tela.exibirQrcode();
//                    } catch (IOException ex) {
//                        Logger.getLogger(PanelDetalheCompra.class.getName()).log(Level.SEVERE, null, ex);
//                    } catch (URISyntaxException ex) {
//                        Logger.getLogger(PanelDetalheCompra.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    
//                    
//                    tela.irTelaInicial();
//                }
//            });
//        
//        
//        
//        panelDados.add(btImprimir);
//        panelDados.add(btVisualizarNoCll);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDados = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        panelDados.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setText("Marcar pelo Celular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDados;
    // End of variables declaration//GEN-END:variables
}
