/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela;

import LogicaBingo.Cartela;
import LogicaBingo.Jogador;
import baixarhtml.FileUploader;
import baixarhtml.GeradorDeQr;
import cartelahtml.ManipularCart;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Jonas
 */
public class PanelDetalheCompra extends javax.swing.JPanel {
    
    //atributos para o o panel de detalhe compra:
    private Tela tela;
    private JButton btCartelas[];
    
    //atributo que serve tanto para o Panel de detalhe compra como a cartela
    private Jogador jogador;
    
    //variaveis para o JDialog da cartela:
    private Cartela cartelaExibir;
    private JLabel lbNumeros[][]= new JLabel[5][5];

    
    
    
    /**
     * Creates new form PanelDetalheCompra
     */
    public PanelDetalheCompra(Tela t, Jogador jogador) {
        initComponents();
        
        //deixando os dialogs no centro da tela:
        jdCartela.setLocationRelativeTo(null);
        jdQrcode.setLocationRelativeTo(null);
        
        //iniciando variaveis para o JDialog da cartela:
        this.jogador= jogador;
        //iniciando labels onde ficara os numeros da cartela:
        for(int i=0; i<lbNumeros.length; i++){
            for(int j=0; j<lbNumeros[0].length; j++){
                lbNumeros[i][j]= new JLabel();
                
                jpNumeros.add(lbNumeros[i][j]); //adicionando a seu panel dos numeros
            }
        }
        
        
        
        //iniciando parte do Panel detalhe compra:
        
        tela= t;
        
        //quantidade de cartelas do jogador que acabou de comprar:
        int qtCartelas= jogador.getQtCartelas();
        
        
        //mudando o panel dos dados para gridLayout com a quantidade de linhas de acordo com a quantidade de cartelas + a linha dos botoes de como salvar cartela e duas colunas 
        panelDados.setLayout(new GridLayout(qtCartelas, 2, 0, 8));
        
        //um botao para cada cartela:
        btCartelas= new JButton[qtCartelas];
        
        for(int i=0; i<qtCartelas; i++){
            String cartelaNum= "Cartela " + String.valueOf(i+1);
            
            JLabel jlb= new JLabel(cartelaNum);
            //ajustando propriedades visuais do label dos numeros
            jlb.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
            jlb.setOpaque(true);
            jlb.setBackground(new java.awt.Color(255, 255, 102));
            jlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            
            //botao para visualizar cartela (adicionado ao lado do seu respectivo label)
            btCartelas[i]= new JButton("Visualizar cartela");
            
            btCartelas[i].addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    
                    Cartela cartelaExibir;
                    
                    //verificando qual botao foi apertado e mostrando a cartela de acordo 
                    for(int i=0; i<btCartelas.length; i++){
                        if(evt.getSource() == btCartelas[i]){
                            cartelaExibir= jogador.getCartelas().get(i);
                            exibirCartela(cartelaExibir);
                            break;
                        }
                    }
                    
                }
            });
            
            //adicionando linha do gridLayout:
            panelDados.add(jlb);
            panelDados.add(btCartelas[i]);
        }
    }
    
                                       



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCartela = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtId = new javax.swing.JLabel();
        txtNomeJogador = new javax.swing.JLabel();
        btMudarCartela = new javax.swing.JButton();
        btVoltarCompra = new javax.swing.JButton();
        jpNumeros = new javax.swing.JPanel();
        jdQrcode = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelDados = new javax.swing.JPanel();
        btMarcarNoCllr = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();

        jdCartela.setModal(true);
        jdCartela.setSize(new java.awt.Dimension(320, 450));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARTELA");
        jPanel4.add(jLabel1);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(java.awt.Color.gray);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        txtId.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtId.setText("ID: ");
        txtId.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(txtId);

        txtNomeJogador.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtNomeJogador.setText("Jogador: ");
        jPanel5.add(txtNomeJogador);

        btMudarCartela.setBackground(new java.awt.Color(255, 255, 204));
        btMudarCartela.setText("Trocar Cartela");
        btMudarCartela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMudarCartelaActionPerformed(evt);
            }
        });
        jPanel5.add(btMudarCartela);

        btVoltarCompra.setBackground(new java.awt.Color(255, 0, 0));
        btVoltarCompra.setText("Voltar");
        btVoltarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarCompraActionPerformed(evt);
            }
        });
        jPanel5.add(btVoltarCompra);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jpNumeros.setBackground(java.awt.Color.gray);
        jpNumeros.setLayout(new java.awt.GridLayout(5, 5));
        jPanel3.add(jpNumeros, java.awt.BorderLayout.CENTER);

        jdCartela.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jdQrcode.setBackground(new java.awt.Color(255, 255, 255));
        jdQrcode.setModal(true);
        jdQrcode.setSize(new java.awt.Dimension(310, 340));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(lbImagem, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Baixe suas cartelas através deste qrcode:");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jdQrcode.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setOpaque(false);

        panelDados.setBackground(new java.awt.Color(255, 255, 102));
        panelDados.setOpaque(false);

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        btMarcarNoCllr.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btMarcarNoCllr.setText("Marcar pelo Celular");
        btMarcarNoCllr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMarcarNoCllrActionPerformed(evt);
            }
        });

        btImprimir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMarcarNoCllr, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMarcarNoCllr, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    
    //metodos para a parte do JDialog do Qrcode
    private void exibirQrcode(){
        String caminhoImg= "src/main/java/baixarhtml/qrcode.png";
        try {
            // Carrega a nova imagem do mesmo caminho usando ImageIO
            BufferedImage imagemBuffered = ImageIO.read(new File(caminhoImg));
            ImageIcon imagemIcon = new ImageIcon(imagemBuffered);
            
            // Atualiza o JLabel com a nova imagem
            lbImagem.setIcon(imagemIcon);
            
            jdQrcode.setVisible(true);
            
            // Repaint não é necessário aqui, pois o setIcon já faz isso.
        } catch (Exception e) {
            e.printStackTrace(); // Para depuração, caso ocorra um erro ao carregar a imagem
        }
    }
    private void btMarcarNoCllrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarcarNoCllrActionPerformed
        // TODO add your handling code here:
        try {
            ManipularCart mc= new ManipularCart();
            mc.addCartelas(jogador);

            GeradorDeQr gerarQr= new GeradorDeQr(FileUploader.getLinkDownload());

            //tela.exibirQrcode();
            exibirQrcode();
        } catch (IOException ex) {
            Logger.getLogger(PanelDetalheCompra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(PanelDetalheCompra.class.getName()).log(Level.SEVERE, null, ex);
        }


        tela.irTelaInicial();
    }//GEN-LAST:event_btMarcarNoCllrActionPerformed

    
    
    //metodos para o JDialog da cartela:
    
    private void exibirCartela(Cartela cartelaExibir){
        this.cartelaExibir= cartelaExibir;
        
        setNumsInterface(cartelaExibir, jogador);
        setLbId(cartelaExibir.getId());
        setLbJogador(jogador.getNome());
        jdCartela.setVisible(true);
    }
    
    private void setNumsInterface(Cartela cart, Jogador dono){
        int[][] cartela= cart.getCartela();
        String nome= dono.getNome();
        
        //jpNumeros= new JPanel(new GridLayout(5,5));
        
        //labels com seus valores de acordo com a cartela
        for(int l=0; l<cartela.length; l++){
            for(int c=0; c<cartela[0].length; c++){
                String num;
                if(cartela[l][c]==0){
                    num= "--";
                }
                else if(cartela[l][c]<=9){
                    num= "0" + String.valueOf(cartela[l][c]);
                }
                else{
                    num= String.valueOf(cartela[l][c]);
                }
                
                lbNumeros[l][c].setText(num);
                
                //centralizando texto:
                lbNumeros[l][c].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                
                //adicionando borda
                lbNumeros[l][c].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
                
                //almentando tamanho da fonte
                lbNumeros[l][c].setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
                
                lbNumeros[l][c].setForeground(Color.black);
                //jpNumeros.add(lbNumeros[l][c]);
            }
        }
    }
    
    
    private void setLbId(int id){
        txtId.setText(("ID: " + String.valueOf(id)));
        txtId.setForeground(Color.black);
    }
    private void setLbJogador(String nome){
        txtNomeJogador.setText("Jogador: " + nome);
        txtNomeJogador.setForeground(Color.black);
    }                                            

    
    private void btMudarCartelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMudarCartelaActionPerformed
        // TODO add your handling code here:

        cartelaExibir.gerarCartela();//regerando cartela

        setNumsInterface(cartelaExibir, jogador); //atualizar label com a cartela atualizada

        //lbNumeros[0][0].setText("kk");
    }//GEN-LAST:event_btMudarCartelaActionPerformed

    private void btVoltarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarCompraActionPerformed
        // TODO add your handling code here:
        //tela.irDetalheCompra(jogador);
        jdCartela.setVisible(false);
    }//GEN-LAST:event_btVoltarCompraActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btMarcarNoCllr;
    private javax.swing.JButton btMudarCartela;
    private javax.swing.JButton btVoltarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDialog jdCartela;
    private javax.swing.JDialog jdQrcode;
    private javax.swing.JPanel jpNumeros;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JPanel panelDados;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNomeJogador;
    // End of variables declaration//GEN-END:variables
}
