/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tela;

import LogicaBingo.Jogador;

/**
 *
 * @author Jonas
 */
public class PanelCompraCartela extends javax.swing.JPanel {
    
    private Tela tela;

    /**
     * Creates new form PanelJogo
     */
    public PanelCompraCartela(Tela t) {
        initComponents();
        tela=t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qtCartelasComprar = new javax.swing.JSpinner();
        btCancelar = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 2));

        jLabel3.setText("nome (opicional):");
        add(jLabel3);
        add(jtNome);

        jLabel4.setText("Quantidade de Cartelas");
        add(jLabel4);

        qtCartelasComprar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(qtCartelasComprar);

        btCancelar.setText("Cancelar");
        add(btCancelar);

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        add(btConfirmar);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        // TODO add your handling code here:
        Integer qtCartelas= (Integer)(qtCartelasComprar.getValue());
        String nome = jtNome.getText()==null? "" : jtNome.getText();
        
        //criando jogador
        Jogador jogador= new Jogador(nome, 2, tela.getBingo());
        
        tela.irDetalheCompra(jogador);
    }//GEN-LAST:event_btConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtNome;
    private javax.swing.JSpinner qtCartelasComprar;
    // End of variables declaration//GEN-END:variables
}
